version: "3"
services:
	app
		container_name: docker-node-mongo
		restart: always # if (fail) restart
		build: . # use Dockerfile from current dir
		ports:
			- "80:3000"
		# originally links, but I think that prop is deprecated
		bridge:
			- mongo
	mongo:
		container_name: mongo
		image: mongo
		ports:
			- "27017:27017"